name: Nx Dynamic CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Rspack CLI
        run: npm install -g @rspack/cli

      - name: Set base and head SHAs
        uses: nrwl/nx-set-shas@v4

      - name: Reset Nx cache
        run: npx nx reset

      - name: Run affected lint
        run: npx nx affected --target=lint --base=$NX_BASE --head=$NX_HEAD --verbose

      - name: Run affected test
        run: npx nx affected --target=test --base=$NX_BASE --head=$NX_HEAD --verbose

      - name: Run affected build
        run: npx nx affected --target=build --base=$NX_BASE --head=$NX_HEAD --verbose
